-- 1. Create the Wishlist table
CREATE TABLE wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_wishlist PRIMARY KEY (id)
);

-- 2. Create the Many-to-Many Join Table
CREATE TABLE wishlist_product (
    wishlist_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT pk_wishlist_product PRIMARY KEY (wishlist_id, product_id)
);

-- 3. Add Foreign Key Constraint for Wishlist -> User
ALTER TABLE wishlist
    ADD CONSTRAINT fk_wishlist_on_user 
    FOREIGN KEY (user_id) REFERENCES users (id) 
    ON DELETE CASCADE;

-- 4. Add Foreign Key Constraint for Join Table -> Wishlist
ALTER TABLE wishlist_product
    ADD CONSTRAINT fk_wishpro_on_wishlist 
    FOREIGN KEY (wishlist_id) REFERENCES wishlist (id) 
    ON DELETE CASCADE;

-- 5. Add Foreign Key Constraint for Join Table -> Product
ALTER TABLE wishlist_product
    ADD CONSTRAINT fk_wishpro_on_product 
    FOREIGN KEY (product_id) REFERENCES product (id) 
    ON DELETE CASCADE;
